export const ADD_TO_FRIENDS = 'users/ADD_TO_FRIENDS';
export const REMOVE_FROM_FRIENDS = 'users/REMOVE_FROM_FRIENDS';
export const SET_USERS = 'users/SET_USERS';
export const SET_CURRENT_PAGE = 'users/SET_CURRENT_PAGE';
export const SET_TOTAL_USERS_COUNT = 'users/SET_TOTAL_USERS_COUNT';
export const SET_FILTER = 'users/SET_FILTER';
export const TOGGLE_IS_FETCHING = 'users/TOGGLE_IS_FETCHING';
export const TOGGLE_IS_FOLLOWING_IN_PROGRESS = 'users/TOGGLE_IS_FOLLOWING_IN_PROGRESS';